### ISSUE TITLE
Backup could not be restored

### ISSUE THREAD

**Issue by melbhab** [oTranscribe/oTranscribe#56]
I accidentally backed out of the browser page and the transcript went back to a much older version. The work is in the history, I see the transcripts but they are not restoring. What can I do? This is hours and hours of work (full interview is 2h long)

**Comment by ejb** [comment]
Hi, do you know how to view localStorage in the developer tools? If not, I can talk you through it.

**Comment by melbhab** [comment]
Hi, no I don't. Using Firegox.

**Comment by ejb** [comment]
Ok. First, could you do me a favour to help me work out what’s causing this problem?

1. Go to http://oTranscribe.com/
2. Go to **Menu** > **Developer** to open the developer tools.
3. Click on the **Console** tab.
4. Take a screenshot and either post it here or email it to otranscribe@elliotbentley.com

Then we can try to restore an old backup:

1. Still in the developer tools, click the **cog icon** in the upper-right hand corner.
2. Check the box that says **Storage**.
3. Click on the new **Storage** tab.
4. Click on the **arrow** next to the text "Local Storage”. 
5. Click on the text that says **http://otranscribe.com**.
6. Find the backup you want. I appreciate this may be difficult due to Firefox’s interface. Note down the (approximately) **12-digit number** associated with the backup you want.
7. Click on the **Console** tab.
8. _(Note that this bit will remove text in the existing document!)_ Paste this into the bottom line, replacing the zeros with your backup's number:

        $('#textbox').html(localStorageManager.getItem("oTranscribe-backup-000000000000") );

**Comment by melbhab** [comment]
![screen shot 2016-04-09 at 4 01 56 pm](https://cloud.githubusercontent.com/assets/18369950/14406139/92fd0a0e-fe6c-11e5-8be5-504cd585e018.png)

**Comment by melbhab** [comment]
It really is difficult to locate the right backup. Any tips? Are they in sort of chronological order?

**Comment by ejb** [comment]
Drat, no error messages. Unfortunately I can't tell what's gone wrong.

Try pasting this into the **Console** and pressing return. it should then show a long list of all of your backups, along with their codes.

    localStorageManager.getArray().forEach(function(file,i){
        console.log('\n\n\n\n============\n',file.key,'\n',$.htmlClean((file.value), {format:true, removeTags: ["div", "p", "span", "img", "pre", "text"]}));
    });

**Comment by melbhab** [comment]
OK, so what should happen after I paste the code for the backup I think I need?

**Comment by ejb** [comment]
It _should_ overwrite the current document with the old backup.

**Comment by melbhab** [comment]
I am getting this message

Object { length: 1, context: HTMLDocument → otranscribe.com, selector: "#textbox", 1 more… }

But nothing changes in the doc itself

**Comment by ejb** [comment]
Ok. What happens when you do this?

    localStorageManager.getItem("oTranscribe-backup-000000000000")

Replacing the zeroes with your number.

**Comment by melbhab** [comment]
OK, that worked! Thank you! I will see if I can find a more recent back up as there are about 10 mins missing but better than nothing.

**Comment by ejb** [comment]
Phew, I'm very glad!
